# -*- coding: utf-8 -*-

from database import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowChange(object):
    def setupUiChange(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(880, 620, 301, 121))
        font = QtGui.QFont()
        font.setFamily("Coolsville")
        font.setPointSize(28)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 10, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 40, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 100, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 130, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 160, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 190, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 220, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 310, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 70, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 250, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 280, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 340, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 370, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 400, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 430, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 460, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 490, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_17.setFont(font)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 520, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_18.setFont(font)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 550, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 580, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_20.setFont(font)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 610, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_21.setFont(font)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 640, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_22.setFont(font)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 670, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_23.setFont(font)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 700, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_24.setFont(font)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_25.setGeometry(QtCore.QRect(10, 730, 521, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_25.setFont(font)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(540, 10, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_26.setFont(font)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(540, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_27.setFont(font)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_28.setGeometry(QtCore.QRect(540, 70, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_28.setFont(font)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_29.setGeometry(QtCore.QRect(540, 100, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_29.setFont(font)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_30.setGeometry(QtCore.QRect(540, 130, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_30.setFont(font)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_31.setGeometry(QtCore.QRect(540, 160, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_31.setFont(font)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_32.setGeometry(QtCore.QRect(540, 190, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_32.setFont(font)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_33.setGeometry(QtCore.QRect(540, 220, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_33.setFont(font)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_34.setGeometry(QtCore.QRect(540, 250, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_34.setFont(font)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_35.setGeometry(QtCore.QRect(540, 280, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_35.setFont(font)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_36.setGeometry(QtCore.QRect(540, 310, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_36.setFont(font)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_37.setGeometry(QtCore.QRect(540, 340, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_37.setFont(font)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_38.setGeometry(QtCore.QRect(540, 370, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_38.setFont(font)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_39.setGeometry(QtCore.QRect(540, 400, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_39.setFont(font)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_40.setGeometry(QtCore.QRect(540, 430, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_40.setFont(font)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_41.setGeometry(QtCore.QRect(540, 460, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_41.setFont(font)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_42.setGeometry(QtCore.QRect(540, 490, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_42.setFont(font)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_43.setGeometry(QtCore.QRect(540, 520, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_43.setFont(font)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_44.setGeometry(QtCore.QRect(540, 550, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_44.setFont(font)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_45.setGeometry(QtCore.QRect(540, 580, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_45.setFont(font)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_46.setGeometry(QtCore.QRect(540, 610, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_46.setFont(font)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_47.setGeometry(QtCore.QRect(540, 640, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_47.setFont(font)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_48.setGeometry(QtCore.QRect(540, 670, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_48.setFont(font)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_49.setGeometry(QtCore.QRect(540, 700, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_49.setFont(font)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_50.setGeometry(QtCore.QRect(540, 730, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_50.setFont(font)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_51.setGeometry(QtCore.QRect(620, 10, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_51.setFont(font)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_52.setGeometry(QtCore.QRect(620, 40, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_52.setFont(font)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_53.setGeometry(QtCore.QRect(620, 70, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_53.setFont(font)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_54.setGeometry(QtCore.QRect(620, 100, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_54.setFont(font)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_55.setGeometry(QtCore.QRect(620, 130, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_55.setFont(font)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_56.setGeometry(QtCore.QRect(620, 160, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_56.setFont(font)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_57.setGeometry(QtCore.QRect(620, 190, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_57.setFont(font)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_58.setGeometry(QtCore.QRect(620, 220, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_58.setFont(font)
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_59.setGeometry(QtCore.QRect(620, 250, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_59.setFont(font)
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_60.setGeometry(QtCore.QRect(620, 280, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_60.setFont(font)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_61.setGeometry(QtCore.QRect(620, 310, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_61.setFont(font)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_62.setGeometry(QtCore.QRect(620, 340, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_62.setFont(font)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_63.setGeometry(QtCore.QRect(620, 370, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_63.setFont(font)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_64.setGeometry(QtCore.QRect(620, 400, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_64.setFont(font)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_65.setGeometry(QtCore.QRect(620, 430, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_65.setFont(font)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_66.setGeometry(QtCore.QRect(620, 460, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_66.setFont(font)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_67.setGeometry(QtCore.QRect(620, 490, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_67.setFont(font)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.lineEdit_68 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_68.setGeometry(QtCore.QRect(620, 520, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_68.setFont(font)
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.lineEdit_69 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_69.setGeometry(QtCore.QRect(620, 550, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_69.setFont(font)
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.lineEdit_70 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_70.setGeometry(QtCore.QRect(620, 580, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_70.setFont(font)
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.lineEdit_71 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_71.setGeometry(QtCore.QRect(620, 610, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_71.setFont(font)
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.lineEdit_72 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_72.setGeometry(QtCore.QRect(620, 640, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_72.setFont(font)
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.lineEdit_73 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_73.setGeometry(QtCore.QRect(620, 670, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_73.setFont(font)
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.lineEdit_74 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_74.setGeometry(QtCore.QRect(620, 700, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_74.setFont(font)
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.lineEdit_75 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_75.setGeometry(QtCore.QRect(620, 730, 191, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_75.setFont(font)
        self.lineEdit_75.setObjectName("lineEdit_75")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_2.setText(_translate("MainWindow", "Сохранить"))
        self.lineEdit.setText(_translate("MainWindow", Q))
        self.lineEdit_2.setText(_translate("MainWindow", W))
        self.lineEdit_4.setText(_translate("MainWindow", E))
        self.lineEdit_5.setText(_translate("MainWindow", R))
        self.lineEdit_6.setText(_translate("MainWindow", T))
        self.lineEdit_7.setText(_translate("MainWindow", Y))
        self.lineEdit_8.setText(_translate("MainWindow", U))
        self.lineEdit_9.setText(_translate("MainWindow", I))
        self.lineEdit_3.setText(_translate("MainWindow", O))
        self.lineEdit_10.setText(_translate("MainWindow", P))
        self.lineEdit_11.setText(_translate("MainWindow", A))
        self.lineEdit_12.setText(_translate("MainWindow", S))
        self.lineEdit_13.setText(_translate("MainWindow", D))
        self.lineEdit_14.setText(_translate("MainWindow", F))
        self.lineEdit_15.setText(_translate("MainWindow", G))
        self.lineEdit_16.setText(_translate("MainWindow", H))
        self.lineEdit_17.setText(_translate("MainWindow", J))
        self.lineEdit_18.setText(_translate("MainWindow", K))
        self.lineEdit_19.setText(_translate("MainWindow", L))
        self.lineEdit_20.setText(_translate("MainWindow", Z))
        self.lineEdit_21.setText(_translate("MainWindow", X))
        self.lineEdit_22.setText(_translate("MainWindow", C))
        self.lineEdit_23.setText(_translate("MainWindow", V))
        self.lineEdit_24.setText(_translate("MainWindow", B))
        self.lineEdit_25.setText(_translate("MainWindow", N))
        self.lineEdit_26.setText(_translate("MainWindow", K1))
        self.lineEdit_27.setText(_translate("MainWindow", K2))
        self.lineEdit_28.setText(_translate("MainWindow", K3))
        self.lineEdit_29.setText(_translate("MainWindow", K4))
        self.lineEdit_30.setText(_translate("MainWindow", K5))
        self.lineEdit_31.setText(_translate("MainWindow", K6))
        self.lineEdit_32.setText(_translate("MainWindow", K7))
        self.lineEdit_33.setText(_translate("MainWindow", K8))
        self.lineEdit_34.setText(_translate("MainWindow", K9))
        self.lineEdit_35.setText(_translate("MainWindow", K10))
        self.lineEdit_36.setText(_translate("MainWindow", K11))
        self.lineEdit_37.setText(_translate("MainWindow", K12))
        self.lineEdit_38.setText(_translate("MainWindow", K13))
        self.lineEdit_39.setText(_translate("MainWindow", K14))
        self.lineEdit_40.setText(_translate("MainWindow", K15))
        self.lineEdit_41.setText(_translate("MainWindow", K16))
        self.lineEdit_42.setText(_translate("MainWindow", K17))
        self.lineEdit_43.setText(_translate("MainWindow", K18))
        self.lineEdit_44.setText(_translate("MainWindow", K19))
        self.lineEdit_45.setText(_translate("MainWindow", K20))
        self.lineEdit_46.setText(_translate("MainWindow", K21))
        self.lineEdit_47.setText(_translate("MainWindow", K22))
        self.lineEdit_48.setText(_translate("MainWindow", K23))
        self.lineEdit_49.setText(_translate("MainWindow", K24))
        self.lineEdit_50.setText(_translate("MainWindow", K25))

        self.lineEdit_51.setText(_translate("MainWindow", P1))
        self.lineEdit_52.setText(_translate("MainWindow", P2))
        self.lineEdit_53.setText(_translate("MainWindow", P3))
        self.lineEdit_54.setText(_translate("MainWindow", P4))
        self.lineEdit_55.setText(_translate("MainWindow", P5))
        self.lineEdit_56.setText(_translate("MainWindow", P6))
        self.lineEdit_57.setText(_translate("MainWindow", P7))
        self.lineEdit_58.setText(_translate("MainWindow", P8))
        self.lineEdit_59.setText(_translate("MainWindow", P9))
        self.lineEdit_60.setText(_translate("MainWindow", P10))
        self.lineEdit_61.setText(_translate("MainWindow", P11))
        self.lineEdit_62.setText(_translate("MainWindow", P12))
        self.lineEdit_63.setText(_translate("MainWindow", P13))
        self.lineEdit_64.setText(_translate("MainWindow", P14))
        self.lineEdit_65.setText(_translate("MainWindow", P15))
        self.lineEdit_66.setText(_translate("MainWindow", P16))
        self.lineEdit_67.setText(_translate("MainWindow", P17))
        self.lineEdit_68.setText(_translate("MainWindow", P18))
        self.lineEdit_69.setText(_translate("MainWindow", P19))
        self.lineEdit_70.setText(_translate("MainWindow", P20))
        self.lineEdit_71.setText(_translate("MainWindow", P21))
        self.lineEdit_72.setText(_translate("MainWindow", P22))
        self.lineEdit_73.setText(_translate("MainWindow", P23))
        self.lineEdit_74.setText(_translate("MainWindow", P24))
        self.lineEdit_75.setText(_translate("MainWindow", P25))
        self.menu.setTitle(_translate("MainWindow", "Расписание"))
        self.action.setText(_translate("MainWindow", "Составить расписание"))
        self.action_2.setText(_translate("MainWindow", "Выход"))
        self.action_3.setText(_translate("MainWindow", "Указать количество пар"))
        self.action_4.setText(_translate("MainWindow", "Изменить данные"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
