# -*- coding: utf-8 -*-

from database import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1193, 800)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(390, 40, 511, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(390, 60, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(390, 80, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(390, 100, 471, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(390, 120, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(390, 140, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(390, 160, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(390, 180, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 200, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(390, 220, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(390, 240, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(390, 260, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(390, 280, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(390, 300, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(390, 320, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(390, 340, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(390, 360, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(390, 380, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.centralwidget)
        self.label_19.setGeometry(QtCore.QRect(390, 400, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(390, 420, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(390, 440, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.centralwidget)
        self.label_22.setGeometry(QtCore.QRect(390, 460, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.centralwidget)
        self.label_23.setGeometry(QtCore.QRect(390, 480, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.centralwidget)
        self.label_24.setGeometry(QtCore.QRect(390, 500, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.centralwidget)
        self.label_25.setGeometry(QtCore.QRect(390, 520, 361, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 81, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 60, 81, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(10, 80, 81, 20))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(10, 100, 81, 20))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 120, 81, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(10, 140, 81, 20))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(10, 160, 81, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(10, 180, 81, 20))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(10, 200, 81, 20))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(10, 220, 81, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(10, 240, 81, 20))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(10, 260, 81, 20))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(10, 280, 81, 20))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_14.setGeometry(QtCore.QRect(10, 300, 81, 20))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_15.setGeometry(QtCore.QRect(10, 320, 81, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_16.setGeometry(QtCore.QRect(10, 340, 81, 20))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 360, 81, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_18.setGeometry(QtCore.QRect(10, 380, 81, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_19.setGeometry(QtCore.QRect(10, 400, 81, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_20.setGeometry(QtCore.QRect(10, 420, 81, 20))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_21.setGeometry(QtCore.QRect(10, 440, 81, 20))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_22.setGeometry(QtCore.QRect(10, 460, 81, 20))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_23.setGeometry(QtCore.QRect(10, 480, 81, 20))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_24.setGeometry(QtCore.QRect(10, 500, 81, 20))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_25.setGeometry(QtCore.QRect(10, 520, 81, 20))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.label_26 = QtWidgets.QLabel(self.centralwidget)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_26.setGeometry(QtCore.QRect(90, 40, 111, 20))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_27.setGeometry(QtCore.QRect(90, 60, 111, 20))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_28.setGeometry(QtCore.QRect(90, 80, 111, 20))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_29.setGeometry(QtCore.QRect(90, 100, 111, 20))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_30.setGeometry(QtCore.QRect(90, 120, 111, 20))
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_31.setGeometry(QtCore.QRect(90, 140, 111, 20))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_32.setGeometry(QtCore.QRect(90, 160, 111, 20))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_33.setGeometry(QtCore.QRect(90, 180, 111, 20))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_34.setGeometry(QtCore.QRect(90, 200, 111, 20))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_35.setGeometry(QtCore.QRect(90, 220, 111, 20))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_36.setGeometry(QtCore.QRect(90, 240, 111, 20))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_37.setGeometry(QtCore.QRect(90, 260, 111, 20))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_38.setGeometry(QtCore.QRect(90, 280, 111, 20))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_39.setGeometry(QtCore.QRect(90, 300, 111, 20))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_40.setGeometry(QtCore.QRect(90, 320, 111, 20))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_41.setGeometry(QtCore.QRect(90, 340, 111, 20))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_42.setGeometry(QtCore.QRect(90, 360, 111, 20))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_43.setGeometry(QtCore.QRect(90, 380, 111, 20))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_44.setGeometry(QtCore.QRect(90, 400, 111, 20))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_45.setGeometry(QtCore.QRect(90, 420, 111, 20))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_46.setGeometry(QtCore.QRect(90, 440, 111, 20))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_47.setGeometry(QtCore.QRect(90, 460, 111, 20))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_48.setGeometry(QtCore.QRect(90, 480, 111, 20))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_49.setGeometry(QtCore.QRect(90, 500, 111, 20))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_50.setGeometry(QtCore.QRect(90, 520, 111, 20))
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.label_27 = QtWidgets.QLabel(self.centralwidget)
        self.label_27.setGeometry(QtCore.QRect(90, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.centralwidget)
        self.label_28.setGeometry(QtCore.QRect(390, 10, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_51.setGeometry(QtCore.QRect(200, 40, 81, 20))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_52.setGeometry(QtCore.QRect(200, 60, 81, 20))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_53.setGeometry(QtCore.QRect(200, 80, 81, 20))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_54.setGeometry(QtCore.QRect(200, 100, 81, 20))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_55.setGeometry(QtCore.QRect(200, 120, 81, 20))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_56.setGeometry(QtCore.QRect(200, 140, 81, 20))
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_57.setGeometry(QtCore.QRect(200, 160, 81, 20))
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_58.setGeometry(QtCore.QRect(200, 180, 81, 20))
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_59.setGeometry(QtCore.QRect(200, 200, 81, 20))
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_60.setGeometry(QtCore.QRect(200, 220, 81, 20))
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_61.setGeometry(QtCore.QRect(200, 240, 81, 20))
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_62.setGeometry(QtCore.QRect(200, 260, 81, 20))
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_63.setGeometry(QtCore.QRect(200, 280, 81, 20))
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_64.setGeometry(QtCore.QRect(200, 300, 81, 20))
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_65.setGeometry(QtCore.QRect(200, 320, 81, 20))
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_66.setGeometry(QtCore.QRect(200, 340, 81, 20))
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_67.setGeometry(QtCore.QRect(200, 360, 81, 20))
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.lineEdit_68 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_68.setGeometry(QtCore.QRect(200, 380, 81, 20))
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.lineEdit_69 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_69.setGeometry(QtCore.QRect(200, 400, 81, 20))
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.lineEdit_70 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_70.setGeometry(QtCore.QRect(200, 420, 81, 20))
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.lineEdit_71 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_71.setGeometry(QtCore.QRect(200, 440, 81, 20))
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.lineEdit_72 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_72.setGeometry(QtCore.QRect(200, 460, 81, 20))
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.lineEdit_73 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_73.setGeometry(QtCore.QRect(200, 480, 81, 20))
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.lineEdit_74 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_74.setGeometry(QtCore.QRect(200, 500, 81, 20))
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.lineEdit_75 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_75.setGeometry(QtCore.QRect(200, 520, 81, 20))
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.lineEdit_76 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_76.setGeometry(QtCore.QRect(280, 40, 101, 20))
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.lineEdit_77 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_77.setGeometry(QtCore.QRect(280, 60, 101, 20))
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.lineEdit_78 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_78.setGeometry(QtCore.QRect(280, 80, 101, 20))
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.lineEdit_79 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_79.setGeometry(QtCore.QRect(280, 100, 101, 20))
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.lineEdit_80 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_80.setGeometry(QtCore.QRect(280, 120, 101, 20))
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.lineEdit_81 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_81.setGeometry(QtCore.QRect(280, 140, 101, 20))
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.lineEdit_82 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_82.setGeometry(QtCore.QRect(280, 160, 101, 20))
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.lineEdit_83 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_83.setGeometry(QtCore.QRect(280, 180, 101, 20))
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.lineEdit_84 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_84.setGeometry(QtCore.QRect(280, 200, 101, 20))
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.lineEdit_85 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_85.setGeometry(QtCore.QRect(280, 220, 101, 20))
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.lineEdit_86 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_86.setGeometry(QtCore.QRect(280, 240, 101, 20))
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.lineEdit_87 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_87.setGeometry(QtCore.QRect(280, 260, 101, 20))
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.lineEdit_88 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_88.setGeometry(QtCore.QRect(280, 280, 101, 20))
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.lineEdit_89 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_89.setGeometry(QtCore.QRect(280, 300, 101, 20))
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.lineEdit_90 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_90.setGeometry(QtCore.QRect(280, 320, 101, 20))
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.lineEdit_91 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_91.setGeometry(QtCore.QRect(280, 340, 101, 20))
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.lineEdit_92 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_92.setGeometry(QtCore.QRect(280, 360, 101, 20))
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.lineEdit_93 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_93.setGeometry(QtCore.QRect(280, 380, 101, 20))
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.lineEdit_94 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_94.setGeometry(QtCore.QRect(280, 400, 101, 20))
        self.lineEdit_94.setObjectName("lineEdit_94")
        self.lineEdit_95 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_95.setGeometry(QtCore.QRect(280, 420, 101, 20))
        self.lineEdit_95.setObjectName("lineEdit_95")
        self.lineEdit_96 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_96.setGeometry(QtCore.QRect(280, 440, 101, 20))
        self.lineEdit_96.setObjectName("lineEdit_96")
        self.lineEdit_97 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_97.setGeometry(QtCore.QRect(280, 460, 101, 20))
        self.lineEdit_97.setObjectName("lineEdit_97")
        self.lineEdit_98 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_98.setGeometry(QtCore.QRect(280, 480, 101, 20))
        self.lineEdit_98.setObjectName("lineEdit_98")
        self.lineEdit_99 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_99.setGeometry(QtCore.QRect(280, 500, 101, 20))
        self.lineEdit_99.setObjectName("lineEdit_99")
        self.lineEdit_100 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_100.setGeometry(QtCore.QRect(280, 520, 101, 20))
        self.lineEdit_100.setObjectName("lineEdit_100")
        self.label_29 = QtWidgets.QLabel(self.centralwidget)
        self.label_29.setGeometry(QtCore.QRect(200, 10, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.centralwidget)
        self.label_30.setGeometry(QtCore.QRect(280, 10, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 550, 301, 121))
        font = QtGui.QFont()
        font.setFamily("Coolsville")
        font.setPointSize(28)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1193, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(MainWindow)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(MainWindow)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(MainWindow)
        self.action_4.setObjectName("action_4")
        self.menu.addAction(self.action_3)
        self.menu.addAction(self.action_4)
        self.menu.addAction(self.action_2)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", Q))
        self.label_2.setText(_translate("MainWindow", W))
        self.label_3.setText(_translate("MainWindow", E))
        self.label_4.setText(_translate("MainWindow", R))
        self.label_5.setText(_translate("MainWindow", T))
        self.label_6.setText(_translate("MainWindow", Y))
        self.label_7.setText(_translate("MainWindow", U))
        self.label_8.setText(_translate("MainWindow", I))
        self.label_9.setText(_translate("MainWindow", O))
        self.label_10.setText(_translate("MainWindow", P))
        self.label_11.setText(_translate("MainWindow", A))
        self.label_12.setText(_translate("MainWindow", S))
        self.label_13.setText(_translate("MainWindow", D))
        self.label_14.setText(_translate("MainWindow", F))
        self.label_15.setText(_translate("MainWindow", G))
        self.label_16.setText(_translate("MainWindow", H))
        self.label_17.setText(_translate("MainWindow", J))
        self.label_18.setText(_translate("MainWindow", K))
        self.label_19.setText(_translate("MainWindow", L))
        self.label_20.setText(_translate("MainWindow", Z))
        self.label_21.setText(_translate("MainWindow", X))
        self.label_22.setText(_translate("MainWindow", C))
        self.label_23.setText(_translate("MainWindow", V))
        self.label_24.setText(_translate("MainWindow", B))
        self.label_25.setText(_translate("MainWindow", N))
        self.lineEdit.setText(_translate("MainWindow", "0"))
        self.lineEdit_2.setText(_translate("MainWindow", "0"))
        self.lineEdit_3.setText(_translate("MainWindow", "0"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.lineEdit_5.setText(_translate("MainWindow", "0"))
        self.lineEdit_6.setText(_translate("MainWindow", "0"))
        self.lineEdit_7.setText(_translate("MainWindow", "0"))
        self.lineEdit_8.setText(_translate("MainWindow", "0"))
        self.lineEdit_9.setText(_translate("MainWindow", "0"))
        self.lineEdit_10.setText(_translate("MainWindow", "0"))
        self.lineEdit_11.setText(_translate("MainWindow", "0"))
        self.lineEdit_12.setText(_translate("MainWindow", "0"))
        self.lineEdit_13.setText(_translate("MainWindow", "0"))
        self.lineEdit_14.setText(_translate("MainWindow", "0"))
        self.lineEdit_15.setText(_translate("MainWindow", "0"))
        self.lineEdit_16.setText(_translate("MainWindow", "0"))
        self.lineEdit_17.setText(_translate("MainWindow", "0"))
        self.lineEdit_18.setText(_translate("MainWindow", "0"))
        self.lineEdit_19.setText(_translate("MainWindow", "0"))
        self.lineEdit_20.setText(_translate("MainWindow", "0"))
        self.lineEdit_21.setText(_translate("MainWindow", "0"))
        self.lineEdit_22.setText(_translate("MainWindow", "0"))
        self.lineEdit_23.setText(_translate("MainWindow", "0"))
        self.lineEdit_24.setText(_translate("MainWindow", "0"))
        self.lineEdit_25.setText(_translate("MainWindow", "0"))
        self.label_26.setText(_translate("MainWindow", "18-101-Д"))
        self.lineEdit_26.setText(_translate("MainWindow", "0"))
        self.lineEdit_27.setText(_translate("MainWindow", "0"))
        self.lineEdit_28.setText(_translate("MainWindow", "0"))
        self.lineEdit_29.setText(_translate("MainWindow", "0"))
        self.lineEdit_30.setText(_translate("MainWindow", "0"))
        self.lineEdit_31.setText(_translate("MainWindow", "0"))
        self.lineEdit_32.setText(_translate("MainWindow", "0"))
        self.lineEdit_33.setText(_translate("MainWindow", "0"))
        self.lineEdit_34.setText(_translate("MainWindow", "0"))
        self.lineEdit_35.setText(_translate("MainWindow", "0"))
        self.lineEdit_36.setText(_translate("MainWindow", "0"))
        self.lineEdit_37.setText(_translate("MainWindow", "0"))
        self.lineEdit_38.setText(_translate("MainWindow", "0"))
        self.lineEdit_39.setText(_translate("MainWindow", "0"))
        self.lineEdit_40.setText(_translate("MainWindow", "0"))
        self.lineEdit_41.setText(_translate("MainWindow", "0"))
        self.lineEdit_42.setText(_translate("MainWindow", "0"))
        self.lineEdit_43.setText(_translate("MainWindow", "0"))
        self.lineEdit_44.setText(_translate("MainWindow", "0"))
        self.lineEdit_45.setText(_translate("MainWindow", "0"))
        self.lineEdit_46.setText(_translate("MainWindow", "0"))
        self.lineEdit_47.setText(_translate("MainWindow", "0"))
        self.lineEdit_48.setText(_translate("MainWindow", "0"))
        self.lineEdit_49.setText(_translate("MainWindow", "0"))
        self.lineEdit_50.setText(_translate("MainWindow", "0"))
        self.label_27.setText(_translate("MainWindow", "18-102-ВТПО"))
        self.label_28.setText(_translate("MainWindow", "Дисциплины"))
        self.lineEdit_51.setText(_translate("MainWindow", "0"))
        self.lineEdit_52.setText(_translate("MainWindow", "0"))
        self.lineEdit_53.setText(_translate("MainWindow", "0"))
        self.lineEdit_54.setText(_translate("MainWindow", "0"))
        self.lineEdit_55.setText(_translate("MainWindow", "0"))
        self.lineEdit_56.setText(_translate("MainWindow", "0"))
        self.lineEdit_57.setText(_translate("MainWindow", "0"))
        self.lineEdit_58.setText(_translate("MainWindow", "0"))
        self.lineEdit_59.setText(_translate("MainWindow", "0"))
        self.lineEdit_60.setText(_translate("MainWindow", "0"))
        self.lineEdit_61.setText(_translate("MainWindow", "0"))
        self.lineEdit_62.setText(_translate("MainWindow", "0"))
        self.lineEdit_63.setText(_translate("MainWindow", "0"))
        self.lineEdit_64.setText(_translate("MainWindow", "0"))
        self.lineEdit_65.setText(_translate("MainWindow", "0"))
        self.lineEdit_66.setText(_translate("MainWindow", "0"))
        self.lineEdit_67.setText(_translate("MainWindow", "0"))
        self.lineEdit_68.setText(_translate("MainWindow", "0"))
        self.lineEdit_69.setText(_translate("MainWindow", "0"))
        self.lineEdit_70.setText(_translate("MainWindow", "0"))
        self.lineEdit_71.setText(_translate("MainWindow", "0"))
        self.lineEdit_72.setText(_translate("MainWindow", "0"))
        self.lineEdit_73.setText(_translate("MainWindow", "0"))
        self.lineEdit_74.setText(_translate("MainWindow", "0"))
        self.lineEdit_75.setText(_translate("MainWindow", "0"))
        self.lineEdit_76.setText(_translate("MainWindow", "0"))
        self.lineEdit_77.setText(_translate("MainWindow", "0"))
        self.lineEdit_78.setText(_translate("MainWindow", "0"))
        self.lineEdit_79.setText(_translate("MainWindow", "0"))
        self.lineEdit_80.setText(_translate("MainWindow", "0"))
        self.lineEdit_81.setText(_translate("MainWindow", "0"))
        self.lineEdit_82.setText(_translate("MainWindow", "0"))
        self.lineEdit_83.setText(_translate("MainWindow", "0"))
        self.lineEdit_84.setText(_translate("MainWindow", "0"))
        self.lineEdit_85.setText(_translate("MainWindow", "0"))
        self.lineEdit_86.setText(_translate("MainWindow", "0"))
        self.lineEdit_87.setText(_translate("MainWindow", "0"))
        self.lineEdit_88.setText(_translate("MainWindow", "0"))
        self.lineEdit_89.setText(_translate("MainWindow", "0"))
        self.lineEdit_90.setText(_translate("MainWindow", "0"))
        self.lineEdit_91.setText(_translate("MainWindow", "0"))
        self.lineEdit_92.setText(_translate("MainWindow", "0"))
        self.lineEdit_93.setText(_translate("MainWindow", "0"))
        self.lineEdit_94.setText(_translate("MainWindow", "0"))
        self.lineEdit_95.setText(_translate("MainWindow", "0"))
        self.lineEdit_96.setText(_translate("MainWindow", "0"))
        self.lineEdit_97.setText(_translate("MainWindow", "0"))
        self.lineEdit_98.setText(_translate("MainWindow", "0"))
        self.lineEdit_99.setText(_translate("MainWindow", "0"))
        self.lineEdit_100.setText(_translate("MainWindow", "0"))
        self.label_29.setText(_translate("MainWindow", "17-201-Д"))
        self.label_30.setText(_translate("MainWindow", "17-202-ВТПО"))
        self.pushButton.setText(_translate("MainWindow", "Составить\n"
"расписание"))
        self.menu.setTitle(_translate("MainWindow", "Расписание"))
        self.action.setText(_translate("MainWindow", "Составить расписание"))
        self.action_2.setText(_translate("MainWindow", "Выход"))
        self.action_3.setText(_translate("MainWindow", "Вернуться обратно"))
        self.action_4.setText(_translate("MainWindow", "Изменить данные"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
